function res = get_pp(inds1, inds2, labels1, labels2, intensity)
    [N, M, ~] = size(intensity);
    res = ...
        (abs(intensity(inds1 + N * M * (labels1 - 1)) - ...
            intensity(inds1 + N * M * (labels2 - 1))) + ...
        abs(intensity(inds2 + N * M * (labels1 - 1)) - ...
            intensity(inds2 + N * M * (labels2 - 1))) ) ;
end